sudo: false
dist: trusty
language: rust
cache: cargo
rust:
  - 1.35.0
branches:
  only:
  - master
addons:
  apt:
    packages:
      - aspell
      - aspell-en
before_script:
  - (cargo install mdbook --git https://github.com/integer32llc/mdBook.git --branch rustdoc_include --force || true)
script:
  - bash ci/build.sh
